//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.RecordOwns = new HashSet<RecordOwn>();
        }
    
        public int BookId { get; set; }
        public string Article { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public Nullable<int> numberOfCopies { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
        public Nullable<int> CurrentOwn { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordOwn> RecordOwns { get; set; }
    }
}
